# Generated by Django 3.2.15 on 2022-10-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward_recieve',
            name='used_point',
            field=models.IntegerField(default=0, verbose_name='使用済ポイント'),
        ),
    ]
