# Generated by Django 3.2.15 on 2022-10-22 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0017_rewardtake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward_recieve',
            name='used_point',
        ),
        migrations.CreateModel(
            name='Used_Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_point', models.IntegerField(default=0, verbose_name='使用済ポイント')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
