# Generated by Django 3.2.15 on 2022-10-22 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0020_ikusei_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardtake',
            name='date',
            field=models.DateField(verbose_name='受けとる日付'),
        ),
        migrations.CreateModel(
            name='Point_Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_limit', models.IntegerField(default=0, verbose_name='残りポイント')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
