# Generated by Django 3.2.15 on 2022-10-22 17:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0021_auto_20221022_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date',
            field=models.DateField(verbose_name='運動活動日'),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(verbose_name='予定概要'),
        ),
        migrations.AlterField(
            model_name='card',
            name='excercise_time',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='予定活動時間'),
        ),
        migrations.AlterField(
            model_name='card',
            name='start_time',
            field=models.TimeField(default=datetime.time(7, 0), verbose_name='運動開始時間'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=200, verbose_name='予定タイトル'),
        ),
        migrations.AlterField(
            model_name='comsumption_point',
            name='comsumption_point',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='消費ポイント'),
        ),
    ]
