# Generated by Django 3.2.15 on 2022-10-22 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0022_auto_20221023_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ikusei',
            name='ikusei_point',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='育成ポイント'),
        ),
        migrations.AlterField(
            model_name='rewardtake',
            name='date',
            field=models.DateField(verbose_name='ご褒美を受けとる日付'),
        ),
    ]
