# Generated by Django 3.2.15 on 2022-10-22 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0023_auto_20221023_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='excercise_time',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(9.9)], verbose_name='予定活動時間'),
        ),
        migrations.AlterField(
            model_name='ikusei',
            name='ikusei_point',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='育成にゲーミフィケーションポイントを使用する'),
        ),
    ]
