# Generated by Django 3.2.15 on 2022-10-23 05:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0024_auto_20221023_0734'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ikusei',
            new_name='Ikusei_Point',
        ),
    ]
