# Generated by Django 3.2.15 on 2022-10-23 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0027_ikusei_suruze'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ikusei_Daze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ikusei_daze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ikusei_suruze')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
