# Generated by Django 3.2.15 on 2022-10-24 01:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0028_ikusei_daze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ikusei_sum',
            name='ikusei_sum',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='育成合計ポイント'),
        ),
    ]
