# Generated by Django 3.2.15 on 2022-10-24 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0029_alter_ikusei_sum_ikusei_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ikusei_point',
            name='ikusei_point',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='育成にゲーミフィケーションポイントを使用する'),
        ),
        migrations.AlterField(
            model_name='ikusei_sum',
            name='ikusei_sum',
            field=models.IntegerField(default=0, verbose_name='育成合計ポイント'),
        ),
    ]
