# Generated by Django 3.2.15 on 2022-11-14 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0032_alter_rewardtake_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comsumption_point',
            name='comsumption_point',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='消費ポイント'),
        ),
        migrations.AlterField(
            model_name='excercise_point',
            name='excercise_Point',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ikusei_point',
            name='ikusei_point',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='育成に運動ポイントを使用する'),
        ),
        migrations.AlterField(
            model_name='ikusei_siyou',
            name='ikusei_siyou',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='育成に運動ポイントを使用する'),
        ),
        migrations.AlterField(
            model_name='reward_recieve',
            name='reward_recieve_point',
            field=models.IntegerField(default=0, verbose_name='運動ポイント'),
        ),
    ]
