# Generated by Django 3.2.15 on 2022-11-14 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0033_auto_20221114_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardtake',
            name='point',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='ご褒美に使用するポイント'),
        ),
    ]
